// AUTO-GENERATED — Current GAS deployment URL
// This file is regenerated by deploy_all.sh on each deploy
// Updated 2026-05-06: v5.18.1-dashboard - Dashboard Modernization + Glassmorphism 2.0
const GAS_CONFIG = {
  url: 'https://script.google.com/macros/s/AKfycbyVK5KLJcHFNfm7oNce5e_WOrFdS2_UuiRQW27ipIUK2DeYGtVjSwWCmr-jIWLnkLcSgw/exec',
  deployDate: '2026-05-06',
  version: 'v5.18.1-dashboard'
};

// Expose globally for all frontend modules
window.GAS_CONFIG = GAS_CONFIG;
window.COMPHONE_GAS_URL = GAS_CONFIG.url;
window.VERSION_CONFIG = GAS_CONFIG; // For runtime version rendering
