(function(global) {
  'use strict';

  const COMPHONE_PWA_ASSETS = {
    styles: [
      'dashboard_shared.css',
      'mobile_shared.css',
      'mobile_glass.css',
      'style.css',
    ],
    scripts: [
      'version_config.js',
      'gas_config.js',
      'pwa_asset_manifest.js',
      'mobile_shared.js',
      'api_contract.js',
      'api_client.js',
      'auth_guard.js',
      'app.js',
      'offline_db.js',
      'app_home.js',
      'app_jobs.js',
      'job_workflow.js',
      'app_actions.js',
      'quick_actions.js',
      'section_vision.js',
      'section_line_center.js',
      'dashboard.js',
      'dashboard_helpers.js',
      'crm_attendance.js',
      'purchase_order.js',
      'section_inventory.js',
      'billing_section.js',
      'billing_customer.js',
      'reports.js',
      'customer_portal.js',
      'analytics_section.js',
      'admin_panel.js',
      'menu_health.js',
      'runtime_self_test.js',
      'notification_center.js',
      'auth.js',
      'error_boundary.js',
      'pwa_install.js',
      'push_notifications.js',
      'section_warranty.js',
      'section_revenue.js',
      'section_tax.js',
      'section_performance.js',
    ],
    precache: [
      '/',
      'index.html',
      'manifest.json',
      'icons/icon-192.png',
      'icons/icon-512.png',
      'version_config.js',
      'gas_config.js',
      'pwa_asset_manifest.js',
      'api_contract.js',
      'dashboard_shared.css',
      'mobile_shared.css',
      'mobile_glass.css',
      'style.css',
      'mobile_shared.js',
      'api_contract.js',
      'api_client.js',
      'auth_guard.js',
      'app.js',
      'offline_db.js',
      'app_home.js',
      'app_jobs.js',
      'job_workflow.js',
      'app_actions.js',
      'quick_actions.js',
      'section_vision.js',
      'section_line_center.js',
      'dashboard.js',
      'dashboard_helpers.js',
      'crm_attendance.js',
      'purchase_order.js',
      'section_inventory.js',
      'billing_section.js',
      'billing_customer.js',
      'reports.js',
      'customer_portal.js',
      'analytics_section.js',
      'admin_panel.js',
      'menu_health.js',
      'runtime_self_test.js',
      'notification_center.js',
      'auth.js',
      'error_boundary.js',
      'pwa_install.js',
      'push_notifications.js',
      'section_warranty.js',
      'section_revenue.js',
      'section_tax.js',
      'section_performance.js',
    ],
  };

  global.COMPHONE_PWA_ASSETS = COMPHONE_PWA_ASSETS;
})(typeof self !== 'undefined' ? self : window);
