# -*- coding: utf-8 -*-
# Generate Index.html V313 — write HTML in chunks to avoid truncation
import os
d = os.path.join(os.path.dirname(__file__), 'Shop_vnext', 'src', 'Index.html')
f = open(d, 'w', encoding='utf-8')
H = f.write  # alias
# ====== HTML HEADER ======
H('<!DOCTYPE html>\n<html lang="th">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Comphone Dashboard V313</title>\n')
H('<script src="https://cdn.tailwindcss.com"><\/script>\n')
H('<script>\ntailwind.config={theme:{extend:{colors:{brand:{DEFAULT:\'#1DB446\',dark:\'#18933a\',light:\'#E8F5E9\'}}}}};\n<\/script>\n')
H("<style>\n@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@300;400;500;600;700;800;900&display=swap');\n")
H("body{font-family:'Noto Sans Thai',-apple-system,sans-serif}\n")
H(".card-hover{transition:all .2s ease}.card-hover:hover{transform:translateY(-2px);box-shadow:0 8px 25px rgba(0,0,0,.1)}\n")
H(".fade-in{animation:fadeIn .3s ease-out}@keyframes fadeIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}\n")
H(".slide-up{animation:slideUp .3s ease-out}@keyframes slideUp{from{transform:translateY(100%)}to{transform:translateY(0)}}\n")
H(".scrollbar-hide::-webkit-scrollbar{display:none}.scrollbar-hide{-ms-overflow-style:none;scrollbar-width:none}\n")
H(".line-clamp-2{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}\n")
H("</style></head>\n")
H('<body class="bg-gray-50 text-gray-800 min-h-screen pb-20 pt-16">\n')
# ====== HEADER BAR ======
H('<header class="fixed top-0 left-0 right-0 z-50 bg-gradient-to-r from-brand to-brand-dark text-white shadow-lg">\n')
H('<div class="max-w-3xl mx-auto px-4 py-3 flex justify-between items-center">\n')
H('<div class="flex items-center gap-2"><span class="text-2xl">&#x1F4F1;</span>\n')
H('<h1 class="text-lg font-extrabold tracking-tight">Comphone Dashboard</h1></div>\n')
H('<div id="clock" class="text-xs font-medium opacity-90 bg-white/20 px-3 py-1 rounded-full">...</div></div></header>\n')
# ====== NAV BAR ======
H('<nav class="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 shadow-[0_-2px_10px_rgba(0,0,0,0.06)]">\n')
H('<div class="max-w-3xl mx-auto flex justify-around py-1">\n')
H('<button id="tabDashboard" class="flex flex-col items-center px-4 py-2 text-xs transition-all text-brand font-bold" onclick="go(\'pageDashboard\')"><span class="text-xl mb-0.5">&#x1F4CA;</span><span>&#x0E2A;&#x0E23;&#x0E38;&#x0E1B;</span></button>\n')
H('<button id="tabJobs" class="flex flex-col items-center px-4 py-2 text-xs transition-all text-gray-400 font-semibold" onclick="go(\'pageJobs\')"><span class="text-xl mb-0.5">&#x1F4CB;</span><span>&#x0E07;&#x0E32;&#x0E19;</span></button>\n')
H('<button id="tabStock" class="flex flex-col items-center px-4 py-2 text-xs transition-all text-gray-400 font-semibold" onclick="go(\'pageStock\')"><span class="text-xl mb-0.5">&#x1F4E6;</span><span>&#x0E2A;&#x0E15;&#x0E47;&#x0E2D;&#x0E01;</span></button>\n')
H('</div></nav>\n')
# ====== MAIN SECTIONS ======
H('<main class="max-w-3xl mx-auto px-4 pt-4">\n')
H('<section id="pageDashboard" class="page active fade-in"></section>\n')
H('<section id="pageJobs" class="page hidden fade-in">\n')

H('<div class="sticky top-16 z-30 bg-gray-50 py-3 -mx-4 px-4">\n')
H('<div class="relative">\n')
H('<span class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">&#x1F50D;</span>\n')
H('<input type="text" id="searchInput" placeholder="&#x0E04;&#x0E49;&#x0E19;&#x0E2B;&#x0E32; JobID, &#x0E0A;&#x0E37;&#x0E48;&#x0E2D;&#x0E25;&#x0E39;&#x0E01;&#x0E04;&#x0E49;&#x0E32;..." class="w-full pl-10 pr-4 py-3 bg-white border-2 border-gray-200 rounded-xl text-sm focus:border-brand focus:outline-none transition-colors shadow-sm">\n')
H('</div>\n')

H('<div class="flex gap-2 mt-3 overflow-x-auto scrollbar-hide pb-1">\n')
H('<button class="filter-btn px-4 py-1.5 bg-brand text-white rounded-full text-xs font-bold" data-filter="all">&#x0E17;&#x0E31;&#x0E49;&#x0E07;&#x0E2B;&#x0E21;&#x0E14;</button>\n')
H('<button class="filter-btn px-4 py-1.5 bg-amber-100 text-amber-700 rounded-full text-xs font-bold" data-filter="&#x0E23;&#x0E2D;&#x0E14;&#x0E33;&#x0E40;&#x0E19;&#x0E34;&#x0E19;&#x0E01;&#x0E32;&#x0E23;">&#x23F3; &#x0E23;&#x0E2D;</button>\n')
H('<button class="filter-btn px-4 py-1.5 bg-blue-100 text-blue-700 rounded-full text-xs font-bold" data-filter="InProgress">&#x1F504; &#x0E17;&#x0E33;</button>\n')
H('<button class="filter-btn px-4 py-1.5 bg-green-100 text-green-700 rounded-full text-xs font-bold" data-filter="Completed">&#x2705; &#x0E40;&#x0E2A;&#x0E23;&#x0E47;&#x0E08;</button>\n')
H('</div></div>\n')
H('<div id="jobCards" class="space-y-3 pb-4"></div></section>\n')
H('<section id="pageStock" class="page hidden fade-in"></section>\n')
H('<section id="pageForm" class="page hidden fade-in">\n')
H('<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 mb-4">\n')
H('<h2 id="formTitle" class="text-lg font-extrabold text-brand mb-4"></h2>\n')
H('<div id="formBody" class="space-y-4"></div></div></section></main>\n')
# ====== FAB ======
H('<button id="fabBtn" class="fixed bottom-20 right-5 w-14 h-14 bg-gradient-to-br from-brand to-brand-dark text-white rounded-full shadow-lg shadow-brand/30 flex items-center justify-center text-2xl font-bold z-40 hover:scale-105 active:scale-95 transition-transform" onclick="openNewJob()">+</button>\n')
# ====== MODALS ======
H('<div id="alertModal" class="fixed inset-0 z-[60] bg-black/50 hidden items-center justify-center p-4" onclick="if(event.target===this)this.classList.add(\'hidden\')">\n')
H('<div class="bg-white rounded-2xl p-6 w-full max-w-sm slide-up text-center">\n')
H('<div id="alertIcon" class="text-4xl mb-3"></div>\n')
H('<h3 id="alertTitle" class="text-lg font-bold mb-2"></h3>\n')
H('<p id="alertMsg" class="text-sm text-gray-500 leading-relaxed mb-5 whitespace-pre-line"></p>\n')
H('<button onclick="document.getElementById(\'alertModal\').classList.add(\'hidden\')" class="w-full py-3 bg-brand text-white rounded-xl font-bold text-sm hover:bg-brand-dark transition-colors">&#x0E15;&#x0E01;&#x0E25;&#x0E07;</button></div></div>\n')
H('<div id="statusModal" class="fixed inset-0 z-[60] bg-black/50 hidden items-end justify-center" onclick="if(event.target===this)this.classList.add(\'hidden\')">\n')
H('<div class="bg-white rounded-t-2xl p-5 w-full max-w-md slide-up">\n')
H('<div class="flex justify-between items-center mb-3">\n')
H('<h3 id="statusTitle" class="text-lg font-bold"></h3>\n')
H('<button onclick="document.getElementById(\'statusModal\').classList.add(\'hidden\')" class="text-2xl text-gray-400 hover:text-gray-600">&times;</button></div>\n')
H('<p id="statusSubtitle" class="text-sm text-gray-500 mb-4"></p>\n')
H('<div id="statusOptions" class="grid grid-cols-2 gap-2 mb-4"></div>\n')
H('<div class="mb-4"><label class="text-xs font-bold text-gray-600 mb-1 block">&#x0E2B;&#x0E21;&#x0E32;&#x0E22;&#x0E40;&#x0E2B;&#x0E15;&#x0E38;&#x0E41;&#x0E15;&#x0E48;&#x0E21;</label>\n')
H('<input type="text" id="statusNote" placeholder="&#x0E40;&#x0E1E;&#x0E37;&#x0E48;&#x0E2D;&#x0E40;&#x0E15;&#x0E37;&#x0E2D;&#x0E21;..." class="w-full px-4 py-2.5 border-2 border-gray-200 rounded-xl text-sm focus:border-brand focus:outline-none"></div>\n')
H('<button id="statusSave" class="w-full py-3 bg-brand text-white rounded-xl font-bold text-sm hover:bg-brand-dark transition-colors disabled:opacity-50" onclick="saveStatus()">&#x0E1A;&#x0E31;&#x0E19;&#x0E17;&#x0E36;&#x0E01;</button></div></div>\n')
H('<div id="loadingOverlay" class="fixed inset-0 z-[70] bg-white/80 hidden items-center justify-center">\n')
H('<div class="text-center"><div class="w-10 h-10 border-4 border-brand border-t-transparent rounded-full animate-spin mx-auto mb-3"></div>\n')
H('<p class="text-sm font-semibold text-gray-500">&#x0E01;&#x0E33;&#x0E25;&#x0E31;&#x0E07;&#x0E42;&#x0E2B;&#x0E25;&#x0E14;...</p></div></div>\n')
# ====== JAVASCRIPT ======
H('<script>\n')
H('// ====== STATE ======\n')
H("var DATA=null,JOBS=[],activeTab='pageDashboard',currentFilter='all',selJobId='',selStatus='';\n")
# NAV
H("\n// ====== NAV ======\n")
H("function go(p){document.querySelectorAll('.page').forEach(function(x){x.classList.add('hidden');x.classList.remove('active')});var e=document.getElementById(p);if(e){e.classList.remove('hidden');e.classList.add('active')}activeTab=p;sn('tabDashboard',p==='pageDashboard');sn('tabJobs',p==='pageJobs');sn('tabStock',p==='pageStock');var f=document.getElementById('fabBtn');f.style.display=(p==='pageDashboard'||p==='pageJobs')?'flex':'none';if(p==='pageDashboard')renderDashboard();else if(p==='pageJobs')renderJobs();else if(p==='pageStock')renderStock()}\n")
H("function sn(id,a){var e=document.getElementById(id);if(!e)return;e.className='flex flex-col items-center px-4 py-2 text-xs transition '+(a?'text-brand font-bold':'text-gray-400 font-semibold')}\n")
# DATA LOAD
H("\n// ====== DATA LOAD ======\n")
H("function loadData(){showL(true);google.script.run.withSuccessHandler(function(d){showL(false);DATA=d;JOBS=(d&&d.jobs)||[];if(!d||!d.summary){document.getElementById('pageDashboard').innerHTML='<div class=\"text-center py-20 text-gray-400\"><div class=\"text-4xl mb-3\">\\u{1F613}</div><p class=\"font-semibold\">\\u0E02\\u0E49\\u0E2D\\u0E21\\u0E39\\u0E25\\u0E44\\u0E21\\u0E48\\u0E16\\u0E39\\u0E01\\u0E15\\u0E49\\u0E2D\\u0E07</p></div>';return}if(DATA.summary.date)document.getElementById('clock').textContent=DATA.summary.date;renderActive()}).withFailureHandler(function(e){showL(false);document.getElementById('pageDashboard').innerHTML='<div class=\"text-center py-20 text-gray-400\"><div class=\"text-4xl mb-3\">\\u274C</div><p class=\"font-semibold\">\\u0E1C\\u0E34\\u0E14\\u0E1E\\u0E25\\u0E32\\u0E14: '+e.message+'</p></div>'}).getDashboardData()}\n")
H("function showL(s){var e=document.getElementById('loadingOverlay');if(s){e.classList.remove('hidden');e.classList.add('flex')}else{e.classList.add('hidden');e.classList.remove('flex')}}\n")
H("function renderActive(){if(activeTab==='pageDashboard')renderDashboard();else if(activeTab==='pageJobs')renderJobs();else if(activeTab==='pageStock')renderStock()}\n")
# DASHBOARD
H("\n// ====== DASHBOARD ======\n")
H("function renderDashboard(){if(!DATA||!DATA.summary)return;var s=DATA.summary,h='';\n")
H("h+='<div class=\"bg-gradient-to-r from-brand-light to-emerald-100 rounded-2xl p-5 mb-4 border border-brand/20\"><div class=\"flex items-center gap-3\"><div class=\"w-12 h-12 bg-brand rounded-xl flex items-center justify-center text-white text-xl shadow-md\">\\u{1F4F1}</div><div><h2 class=\"text-lg font-extrabold text-brand-dark\">\\u0E22\\u0E34\\u0E19\\u0E14\\u0E35\\u0E15\\u0E49\\u0E2D\\u0E19\\u0E23\\u0E31\\u0E1A</h2><p class=\"text-xs text-gray-500\">Comphone Super App \\u2014 \\u0E23\\u0E30\\u0E1A\\u0E1A\\u0E08\\u0E31\\u0E14\\u0E01\\u0E32\\u0E23\\u0E07\\u0E32\\u0E19\\u0E0A\\u0E48\\u0E32\\u0E07</p></div></div></div>';\n")
H("h+='<div class=\"grid grid-cols-2 gap-3 mb-4\">';")
H("h+=tile(''+(s.pending||0),'\\u0E23\\u0E2D\\u0E14\\u0E33\\u0E40\\u0E19\\u0E34\\u0E19\\u0E01\\u0E32\\u0E23','bg-amber-50 border-amber-200','text-amber-600','\\u23F3');")
H("h+=tile(''+(s.inProgress||0),'\\u0E01\\u0E33\\u0E25\\u0E31\\u0E07\\u0E17\\u0E33','bg-blue-50 border-blue-200','text-blue-600','\\u{1F504}');")
H("h+=tile(''+(s.completed||0),'\\u0E40\\u0E2A\\u0E23\\u0E47\\u0E08\\u0E41\\u0E25\\u0E49\\u0E27','bg-green-50 border-green-200','text-green-600','\\u2705');")
H("h+=tile(''+(s.lowStock||0),'\\u0E2A\\u0E15\\u0E47\\u0E2D\\u0E01\\u0E15\\u0E48\\u0E33','bg-red-50 border-red-200','text-red-600','\\u{1F6A8}');")
H("h+='</div>';\n")
H("h+='<div class=\"bg-white rounded-2xl p-4 shadow-sm border border-gray-100 mb-4\">';h+='<h3 class=\"text-sm font-bold text-gray-700 mb-3\">\\u0E02\\u0E49\\u0E2D\\u0E21\\u0E39\\u0E25\\u0E23\\u0E27\\u0E21</h3>';\n")
H("h+=row2('\\u0E07\\u0E32\\u0E19\\u0E17\\u0E31\\u0E49\\u0E07\\u0E2B\\u0E21\\u0E14',(s.totalJobs||0)+' \\u0E07\\u0E32\\u0E19');")
H("h+=row2('\\u0E2D\\u0E30\\u0E44\\u0E25\\u0E48\\u0E43\\u0E19\\u0E23\\u0E30\\u0E1A\\u0E1A',(s.totalItems||0)+' \\u0E23\\u0E32\\u0E22\\u0E01\\u0E32\\u0E23');")
H("h+='<div class=\"flex justify-between items-center pt-2\"><span class=\"text-xs text-gray-500\">\\u0E2D\\u0E31\\u0E1B\\u0E40\\u0E14\\u0E15\\u0E25\\u0E48\\u0E32\\u0E2A\\u0E38\\u0E14</span><span class=\"font-bold text-xs text-gray-400\">'+(s.date||'-')+'</span></div></div>';\n")
H("h+='<button onclick=\"openNewJob()\" class=\"w-full py-4 bg-gradient-to-r from-brand to-brand-dark text-white rounded-2xl font-bold text-base shadow-lg shadow-brand/20 hover:shadow-xl hover:scale-[1.01] active:scale-[0.99] transition-all mb-3\">\\u2795 \\u0E40\\u0E1B\\u0E34\\u0E14\\u0E07\\u0E32\\u0E19\\u0E43\\u0E2B\\u0E21\\u0E48</button>';\n")
H("h+='<div class=\"bg-blue-50 border border-blue-200 rounded-xl p-4 text-xs text-blue-700 leading-relaxed\">\\u{1F4A1} \\u0E01\\u0E14 \\u0E41\\u0E17\\u0E47\\u0E1A \\u0E07\\u0E32\\u0E19 \\u0E14\\u0E39\\u0E23\\u0E32\\u0E22 \\u2022 \\u0E01\\u0E14 \\u0E41\\u0E17\\u0E47\\u0E1A \\u0E2A\\u0E15\\u0E47\\u0E2D\\u0E01 \\u0E40\\u0E0A\\u0E47\\u0E04\\u0E2D\\u0E30\\u0E44\\u0E25\\u0E48 \\u2022 \\u0E01\\u0E14 + \\u0E40\\u0E1B\\u0E34\\u0E14\\u0E07\\u0E32\\u0E19\\u0E43\\u0E2B\\u0E21\\u0E48</div>';\n")
H("document.getElementById('pageDashboard').innerHTML=h}\n")
H("function tile(n,l,bg,c,ic){return '<div class=\"'+bg+' rounded-2xl p-4 border card-hover\"><div class=\"flex justify-between mb-1\"><span class=\"text-3xl font-black '+c+'\">'+n+'</span><span class=\"text-lg opacity-60\">'+ic+'</span></div><p class=\"text-xs font-medium '+c+'\">'+l+'</p></div>'}\n")
H("function row2(l,v){return '<div class=\"flex justify-between py-2 border-b border-gray-100\"><span class=\"text-xs text-gray-500\">'+l+'</span><span class=\"font-bold text-sm\">'+v+'</span></div>'}\n")
# JOBS RENDER
H("\n// ====== JOBS ======\n")
H("function renderJobs(flist){var list=flist||JOBS;if(currentFilter!=='all'&&!flist){list=[];for(var i=0;i<JOBS.length;i++){if(JOBS[i].status===currentFilter)list.push(JOBS[i])}}var c=document.getElementById('jobCards');if(!list.length){c.innerHTML='<div class=\"text-center py-16 text-gray-400\"><div class=\"text-4xl mb-3\">\\u{1F4CB}</div><p class=\"font-semibold\">\\u0E44\\u0E21\\u0E48\\u0E1E\\u0E1A\\u0E07\\u0E32\\u0E19</p></div>';return}var h='';var lim=Math.min(list.length,50);for(var i=0;i<lim;i++)h+=jcard(list[i]);c.innerHTML=h;bindJobs()}\n")
H("function jcard(j){var sc=gCls(j.status);var sl=gLbl(j.status);var sb=gBdr(j.status);return '<div class=\"bg-white rounded-2xl shadow-sm '+sb+' p-4 card-hover fade-in\"><div class=\"flex justify-between items-start mb-2\">')\n")
# fix: the above line is wrong. Let me rewrite jcard properly
# Actually the last H() call above was wrong — let me fix it properly by overwriting
# Let me just continue properly from this function
pass
# ====== I'll close file and rewrite completely using a proper approach ======
f.close()
print("Phase 1 done, will rewrite completely")
