# -*- coding: utf-8 -*-
"""V319 — Clean Dashboard + UI Polish + LINE Button (Part A: HTML+CSS)"""
import os
d = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'Shop_vnext', 'src', 'Index.html')
f = open(d, 'w', encoding='utf-8')

lines = [
'<!DOCTYPE html>',
'<html lang="th">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>Comphone Dashboard V319</title>',
'<style>',
'*{margin:0;padding:0;box-sizing:border-box}',
'body{font-family:-apple-system,sans-serif;background:linear-gradient(135deg,#f0f4f0,#f5f5f5);color:#333;min-height:100vh}',
'',
'/* Header */',
'.hd{background:linear-gradient(135deg,#1DB446,#158e3a);color:#fff;padding:16px;text-align:center;position:fixed;top:0;left:0;right:0;z-index:10;box-shadow:0 4px 12px rgba(29,180,70,.3)}',
'.hd h1{font-size:18px;font-weight:800}',
'.hd .sub{font-size:11px;opacity:.85;margin-top:2px}',
'',
'/* Loading */',
'#ld{text-align:center;padding:60px 20px}',
'#ld .sp{width:48px;height:48px;border:4px solid #ddd;border-top:4px solid #1DB446;border-radius:50%;animation:sp 1s linear infinite;margin:0 auto 16px}',
'@keyframes sp{to{transform:rotate(360deg)}}',
'#ld p{font-size:16px;color:#666}',
'#ld .hint{font-size:12px;color:#999;margin-top:8px}',
'',
'/* Error box */',
'#eb{display:none;background:#fee;border:2px solid #c33;padding:16px;margin:16px;border-radius:12px}',
'#eb h3{color:#c33;margin-bottom:8px}',
'#eb pre{white-space:pre-wrap;font-size:13px;color:#600}',
'',
'/* Result */',
'#rb{display:none;padding:16px}',
'',
'/* Content container */',
'.ct{padding-top:70px;padding-bottom:80px}',
'',
'/* Tiles */',
'.tl{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:0 8px;margin-bottom:16px}',
'.te{background:#fff;border-radius:16px;padding:16px 8px;text-align:center;box-shadow:0 4px 16px rgba(0,0,0,.06);border:1px solid rgba(0,0,0,.04);transition:transform .2s,box-shadow .2s}',
'.te:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.1)}',
'.te .n{font-size:28px;font-weight:800}',
'.te .l{font-size:11px;color:#888;margin-top:4px;line-height:1.3}',
'.am{color:#E65C00}.bl{color:#1565C0}.gr{color:#2E7D32}.rd{color:#C62828}',
'',
'/* Card */',
'.ca{background:#fff;border-radius:16px;padding:16px;margin:0 8px 12px;box-shadow:0 2px 12px rgba(0,0,0,.05);border:1px solid rgba(0,0,0,.04)}',
'.ca h3{margin:0 0 12px;font-size:15px;font-weight:700;color:#333}',
'.info{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #f0f0f0}',
'.info:last-child{border-bottom:none}',
'.info .lb{font-size:12px;color:#888}',
'.info .vl{font-size:13px;font-weight:600}',
'',
'/* Job card */',
'.jc{background:#fff;border-radius:14px;padding:14px;margin:0 8px 8px;box-shadow:0 2px 8px rgba(0,0,0,.04);cursor:pointer;transition:all .15s;border-left:4px solid #ccc;border:1px solid rgba(0,0,0,.04)}',
'.jc.am{border-left:4px solid #E65C00}',
'.jc.bl{border-left:4px solid #1565C0}',
'.jc.gr{border-left:4px solid #2E7D32}',
'.jc.rd{border-left:4px solid #C62828}',
'.jc:hover{background:#f8fdf8;transform:translateX(4px)}',
'.jc .jid{font-size:13px;font-weight:800;color:#1DB446}',
'.jc .jnm{font-size:14px;font-weight:600;margin:2px 0}',
'.jc .jst{font-size:11px;font-weight:600;padding:2px 8px;border-radius:8px;display:inline-block}',
'.jc .jst.am{background:#FFF3E0;color:#E65C00}',
'.jc .jst.bl{background:#E3F2FD;color:#1565C0}',
'.jc .jst.gr{background:#E8F5E9;color:#2E7D32}',
'.jc .jst.rd{background:#FFEBEE;color:#C62828}',
'.jc .jmeta{font-size:11px;color:#999;margin-top:6px}',
'',
'/* Buttons */',
'.btn{display:block;margin:12px 8px;padding:14px;background:linear-gradient(135deg,#1DB446,#158e3a);color:#fff;border:none;border-radius:12px;font-size:14px;font-weight:700;cursor:pointer;text-align:center;box-shadow:0 4px 12px rgba(29,180,70,.25);transition:all .2s}',
'.btn:hover{transform:translateY(-1px);box-shadow:0 6px 16px rgba(29,180,70,.35)}',
'.btn:active{transform:scale(.98)}',
'.btn.ln{background:linear-gradient(135deg,#06C755,#05a848);box-shadow:0 4px 12px rgba(6,199,85,.25)}',
'.btn.rd{background:linear-gradient(135deg,#FF5252,#e04848);box-shadow:0 4px 12px rgba(255,82,82,.25)}',
'.b2{display:inline-block;margin:4px;padding:8px 14px;border:none;border-radius:8px;font-size:12px;font-weight:600;cursor:pointer}',
'.bb{background:#1565C0;color:#fff}.ba{background:#E65C00;color:#fff}.bp{background:#7B1FA2;color:#fff}.bx{background:#999;color:#fff}',
'',
'/* Modal */',
'#mo{display:none;position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.5);z-index:100;justify-content:center;align-items:center}',
'#mo.op{display:flex}',
'#mb{background:#fff;border-radius:20px;padding:24px;width:90%;max-width:420px;max-height:80vh;overflow-y:auto;animation:mi .25s ease;box-shadow:0 20px 60px rgba(0,0,0,.2)}',
'@keyframes mi{from{transform:scale(.9)translateY(20px);opacity:0}to{transform:scale(1)translateY(0);opacity:1}}',
'#mb h2{font-size:16px;font-weight:800;margin-bottom:4px;color:#333}',
'#mb .su{font-size:13px;color:#666;margin-bottom:12px}',
'#mb .dt{font-size:13px;line-height:1.6;margin-bottom:16px;white-space:pre-line}',
'#mb .ac{display:flex;gap:8px;flex-wrap:wrap}',
'#mb .cx{position:absolute;top:12px;right:16px;background:none;border:none;font-size:24px;cursor:pointer;color:#999;width:32px;height:32px;display:flex;align-items:center;justify-content:center;border-radius:50%;transition:background .2s}',
'#mb .cx:hover{background:#f0f0f0}',
'input[type="text"],textarea{width:100%;padding:12px;border:2px solid #e8e8e8;border-radius:10px;font-size:14px;font-family:inherit;transition:border-color .2s}',
'input[type="text"]:focus,textarea:focus{border-color:#1DB446;outline:none}',
'textarea{resize:vertical;min-height:60px}',
'',
'/* Stock item */',
'.si{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid #f5f5f5}',
'.si:last-child{border-bottom:none}',
'.si .sn{font-size:13px;font-weight:600}',
'.si .sq{font-size:16px;font-weight:800;padding:2px 10px;border-radius:8px}',
'.si .sq.lo{background:#FFEBEE;color:#C62828}',
'.si .sq.ok{background:#E8F5E9;color:#2E7D32}',
'.si .sc{font-size:11px;color:#999}',
'',
'/* Badge */',
'.badge{display:inline-block;font-size:10px;padding:2px 8px;border-radius:10px;font-weight:600}',
'.badge.gn{background:#E8F5E9;color:#2E7D32}',
'',
'/* Responsive */',
'@media(max-width:400px){.tl{grid-template-columns:repeat(2,1fr)}}',
'',
'</style></head>',
'<body>',
]
f.write('\n'.join(lines))
f.close()
print(f"Part A done: {os.path.getsize(d)} bytes")
