"""
Professional Daily Report for Pending Jobs
"""

import pandas as pd
from datetime import datetime

def generate_daily_report():
    """Generate professional daily job report"""
    
    # Read job data
    df = pd.read_csv('C:/Users/Server/.openclaw/workspace/shop/DB_JOBS.csv')
    
    # Only show pending jobs (not completed)
    pending = df[df['status'] != 'Completed'].copy()
    
    # Report Header
    print("=" * 60)
    print("DAILY WORK REPORT - COMPHONE & ELECTRONICS")
    print("=" * 60)
    print(f"Date: {datetime.now().strftime('%d/%m/%Y')}")
    print(f"Time: {datetime.now().strftime('%H:%M')}")
    print(f"Total Pending Jobs: {len(pending)}")
    print()
    
    if len(pending) == 0:
        print("✅ No pending jobs - all tasks completed!")
        return
    
    # Group by customer
    customers = pending['customer_name'].unique()
    
    for i, customer in enumerate(customers, 1):
        if pd.notna(customer) and str(customer).strip():
            customer_jobs = pending[pending['customer_name'] == customer]
            
            print(f"👤 CUSTOMER #{i}: {customer}")
            print("-" * 50)
            print(f"📊 Total Jobs: {len(customer_jobs)}")
            print()
            
            # Display jobs for this customer
            for _, job in customer_jobs.iterrows():
                job_id = job.get('job_id', 'N/A')
                status = job.get('status', 'Unknown')
                location = job.get('location', 'N/A')
                technician = job.get('technician', 'Unassigned')
                
                # Status icon
                if status in ['Urgent', 'URGENT', 'Priority_Personal']:
                    status_icon = '🔥'
                elif status == 'In_Progress':
                    status_icon = '🟡'
                else:
                    status_icon = '📋'
                
                # Technician status
                if technician in ['Unassigned', '', 'nan']:
                    tech_icon = '⚠️'
                else:
                    tech_icon = '✅'
                
                print(f"  {status_icon} Job ID: {job_id}")
                print(f"     Status: {status}")
                print(f"     Location: {location}")
                print(f"     Technician: {tech_icon} {technician}")
                print()
            
            print()  # Empty line between customers
    
    # Summary Section
    print("📈 SUMMARY STATISTICS")
    print("=" * 30)
    
    # Status breakdown
    status_counts = pending['status'].value_counts()
    print("Status Breakdown:")
    for status, count in status_counts.items():
        print(f"  • {status}: {count} jobs")
    
    # Technician assignment
    unassigned = len(pending[pending['technician'].isna() | (pending['technician'] == '')])
    assigned = len(pending) - unassigned
    
    print(f"\nTechnician Assignment:")
    print(f"  • Assigned: {assigned} jobs")
    print(f"  • Unassigned: {unassigned} jobs")
    
    # Urgent jobs
    urgent = len(pending[pending['status'].isin(['Urgent', 'URGENT', 'Priority_Personal'])])
    print(f"\n🔥 Urgent Jobs: {urgent}")
    
    print("\n" + "=" * 60)
    print("Report generated by Comphone System")
    print("For questions: @คอมโฟน")

if __name__ == "__main__":
    generate_daily_report()